modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/trikzon/transparent/issues" #optional

[[mods]] #mandatory
modId="transparent" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Transparent" #mandatory
#updateJSONURL="" #optional
displayURL="https://github.com/trikzon/transparent" #optional
logoFile="assets/transparent/icon.png" #optional
#credits="" #optional
authors="Trikzon" #optional
description='''
Transparent allows resource packs to give certain entities textures with transparent (or translucent) pixels.

To use, simply install the mod and use or create a resource pack that gives one of the supported entities a transparent texture.
'''

[[dependencies.transparent]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

[[dependencies.transparent]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.transparent]]
    modId="ash_api"
    mandatory=true
    versionRange="[3.0.0,)"
